"""Add column uuid to User model

Revision ID: 597d9bdbba1e
Revises: 916e150f9d2e
Create Date: 2021-12-11 09:27:06.051228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '597d9bdbba1e'
down_revision = '916e150f9d2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('uuid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'uuid')
    # ### end Alembic commands ###
