"""modif

Revision ID: 5a45d5b36426
Revises: 60d737902962
Create Date: 2021-10-27 18:43:08.427098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a45d5b36426'
down_revision = '60d737902962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistantmanager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assistant_id', sa.Integer(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assistant_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assistantmanager_id'), 'assistantmanager', ['id'], unique=False)
    op.create_table('doctormanager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctormanager_id'), 'doctormanager', ['id'], unique=False)
    op.create_table('doctorpatient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctorpatient_id'), 'doctorpatient', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doctorpatient_id'), table_name='doctorpatient')
    op.drop_table('doctorpatient')
    op.drop_index(op.f('ix_doctormanager_id'), table_name='doctormanager')
    op.drop_table('doctormanager')
    op.drop_index(op.f('ix_assistantmanager_id'), table_name='assistantmanager')
    op.drop_table('assistantmanager')
    # ### end Alembic commands ###
