"""Modiify new tables

Revision ID: 60d737902962
Revises: b7eaa01cee2c
Create Date: 2021-10-27 16:55:32.812396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60d737902962'
down_revision = 'b7eaa01cee2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('remarque', sa.String(), nullable=True),
    sa.Column('note_created', sa.Boolean(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_id'), 'voice', ['id'], unique=False)
    op.create_index(op.f('ix_voice_path'), 'voice', ['path'], unique=False)
    op.create_index(op.f('ix_voice_remarque'), 'voice', ['remarque'], unique=False)
    op.create_index(op.f('ix_voice_title'), 'voice', ['title'], unique=False)
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_txt', sa.String(), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=True),
    sa.Column('voice_id', sa.Integer(), nullable=True),
    sa.Column('assistant_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('modifier_id', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assistant_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['modifier_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['voice_id'], ['voice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_content_txt'), 'note', ['content_txt'], unique=False)
    op.create_index(op.f('ix_note_id'), 'note', ['id'], unique=False)
    op.drop_constraint('item_owner_id_fkey', 'item', type_='foreignkey')
    op.drop_column('item', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('item_owner_id_fkey', 'item', 'user', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_note_id'), table_name='note')
    op.drop_index(op.f('ix_note_content_txt'), table_name='note')
    op.drop_table('note')
    op.drop_index(op.f('ix_voice_title'), table_name='voice')
    op.drop_index(op.f('ix_voice_remarque'), table_name='voice')
    op.drop_index(op.f('ix_voice_path'), table_name='voice')
    op.drop_index(op.f('ix_voice_id'), table_name='voice')
    op.drop_table('voice')
    # ### end Alembic commands ###
