"""Add column

Revision ID: 9f46b998eba6
Revises: c92de40ccb70
Create Date: 2022-01-18 16:58:26.412798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f46b998eba6'
down_revision = 'c92de40ccb70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voice', sa.Column('folder_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voice', 'folder_id')
    # ### end Alembic commands ###
